# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
# see also https://docs.travis-ci.com/user/languages/r

# see also https://docs.travis-ci.com/user/multi-os/
# You will need to set sudo: false in order to use the container based builds
# and package caching.

# Using the package cache to store R package dependencies can significantly
# speed up build times and is recommended for most builds.
cache:
  - packages

sudo: required

dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

r_packages:
  - mgcv

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - taiyun/corrplot

